services:
  tf-gpu:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tf-gpu-dev
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
